# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import taxos_service_pb2 as taxos__service__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in taxos_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaxosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBucket = channel.unary_unary(
                '/taxos.TaxosService/CreateBucket',
                request_serializer=taxos__service__pb2.CreateBucketRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.Bucket.FromString,
                _registered_method=True)
        self.GetBucket = channel.unary_unary(
                '/taxos.TaxosService/GetBucket',
                request_serializer=taxos__service__pb2.GetBucketRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.Bucket.FromString,
                _registered_method=True)
        self.ListBuckets = channel.unary_unary(
                '/taxos.TaxosService/ListBuckets',
                request_serializer=taxos__service__pb2.ListBucketsRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.ListBucketsResponse.FromString,
                _registered_method=True)
        self.UpdateBucket = channel.unary_unary(
                '/taxos.TaxosService/UpdateBucket',
                request_serializer=taxos__service__pb2.UpdateBucketRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.Bucket.FromString,
                _registered_method=True)
        self.DeleteBucket = channel.unary_unary(
                '/taxos.TaxosService/DeleteBucket',
                request_serializer=taxos__service__pb2.DeleteBucketRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateReceipt = channel.unary_unary(
                '/taxos.TaxosService/CreateReceipt',
                request_serializer=taxos__service__pb2.CreateReceiptRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.Receipt.FromString,
                _registered_method=True)
        self.GetReceipt = channel.unary_unary(
                '/taxos.TaxosService/GetReceipt',
                request_serializer=taxos__service__pb2.GetReceiptRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.Receipt.FromString,
                _registered_method=True)
        self.ListReceipts = channel.unary_unary(
                '/taxos.TaxosService/ListReceipts',
                request_serializer=taxos__service__pb2.ListReceiptsRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.ListReceiptsResponse.FromString,
                _registered_method=True)
        self.UpdateReceipt = channel.unary_unary(
                '/taxos.TaxosService/UpdateReceipt',
                request_serializer=taxos__service__pb2.UpdateReceiptRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.Receipt.FromString,
                _registered_method=True)
        self.DeleteReceipt = channel.unary_unary(
                '/taxos.TaxosService/DeleteReceipt',
                request_serializer=taxos__service__pb2.DeleteReceiptRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.Empty.FromString,
                _registered_method=True)
        self.GetDashboard = channel.unary_unary(
                '/taxos.TaxosService/GetDashboard',
                request_serializer=taxos__service__pb2.GetDashboardRequest.SerializeToString,
                response_deserializer=taxos__service__pb2.DashboardResponse.FromString,
                _registered_method=True)


class TaxosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBucket(self, request, context):
        """Bucket operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReceipt(self, request, context):
        """Receipt operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReceipts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDashboard(self, request, context):
        """Dashboard operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaxosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBucket,
                    request_deserializer=taxos__service__pb2.CreateBucketRequest.FromString,
                    response_serializer=taxos__service__pb2.Bucket.SerializeToString,
            ),
            'GetBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBucket,
                    request_deserializer=taxos__service__pb2.GetBucketRequest.FromString,
                    response_serializer=taxos__service__pb2.Bucket.SerializeToString,
            ),
            'ListBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBuckets,
                    request_deserializer=taxos__service__pb2.ListBucketsRequest.FromString,
                    response_serializer=taxos__service__pb2.ListBucketsResponse.SerializeToString,
            ),
            'UpdateBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBucket,
                    request_deserializer=taxos__service__pb2.UpdateBucketRequest.FromString,
                    response_serializer=taxos__service__pb2.Bucket.SerializeToString,
            ),
            'DeleteBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBucket,
                    request_deserializer=taxos__service__pb2.DeleteBucketRequest.FromString,
                    response_serializer=taxos__service__pb2.Empty.SerializeToString,
            ),
            'CreateReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReceipt,
                    request_deserializer=taxos__service__pb2.CreateReceiptRequest.FromString,
                    response_serializer=taxos__service__pb2.Receipt.SerializeToString,
            ),
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=taxos__service__pb2.GetReceiptRequest.FromString,
                    response_serializer=taxos__service__pb2.Receipt.SerializeToString,
            ),
            'ListReceipts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReceipts,
                    request_deserializer=taxos__service__pb2.ListReceiptsRequest.FromString,
                    response_serializer=taxos__service__pb2.ListReceiptsResponse.SerializeToString,
            ),
            'UpdateReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReceipt,
                    request_deserializer=taxos__service__pb2.UpdateReceiptRequest.FromString,
                    response_serializer=taxos__service__pb2.Receipt.SerializeToString,
            ),
            'DeleteReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReceipt,
                    request_deserializer=taxos__service__pb2.DeleteReceiptRequest.FromString,
                    response_serializer=taxos__service__pb2.Empty.SerializeToString,
            ),
            'GetDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboard,
                    request_deserializer=taxos__service__pb2.GetDashboardRequest.FromString,
                    response_serializer=taxos__service__pb2.DashboardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taxos.TaxosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taxos.TaxosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaxosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/CreateBucket',
            taxos__service__pb2.CreateBucketRequest.SerializeToString,
            taxos__service__pb2.Bucket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/GetBucket',
            taxos__service__pb2.GetBucketRequest.SerializeToString,
            taxos__service__pb2.Bucket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/ListBuckets',
            taxos__service__pb2.ListBucketsRequest.SerializeToString,
            taxos__service__pb2.ListBucketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/UpdateBucket',
            taxos__service__pb2.UpdateBucketRequest.SerializeToString,
            taxos__service__pb2.Bucket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/DeleteBucket',
            taxos__service__pb2.DeleteBucketRequest.SerializeToString,
            taxos__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/CreateReceipt',
            taxos__service__pb2.CreateReceiptRequest.SerializeToString,
            taxos__service__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/GetReceipt',
            taxos__service__pb2.GetReceiptRequest.SerializeToString,
            taxos__service__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReceipts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/ListReceipts',
            taxos__service__pb2.ListReceiptsRequest.SerializeToString,
            taxos__service__pb2.ListReceiptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/UpdateReceipt',
            taxos__service__pb2.UpdateReceiptRequest.SerializeToString,
            taxos__service__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/DeleteReceipt',
            taxos__service__pb2.DeleteReceiptRequest.SerializeToString,
            taxos__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taxos.TaxosService/GetDashboard',
            taxos__service__pb2.GetDashboardRequest.SerializeToString,
            taxos__service__pb2.DashboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
