FROM mcr.microsoft.com/devcontainers/base:bookworm

# Install buf for protobuf generation
RUN curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.28.1/buf-Linux-x86_64" -o /usr/local/bin/buf && \
  chmod +x /usr/local/bin/buf
